In [39]:
# 데이터 전처리
    # 결측치 처리
    # 클래스불균형 확인 및 처리

# 특성공학 : 피처선정 또는 피처생성

# 베이스 모델 선정
    # 분류모델 : LogisticRegression
    # 클래스 리포트, 과적합여부

# 베이스 모델의 성능을 상회하는 모델과 하이퍼 파라미터 조합을 찾아서 성능을 출력

In [40]:
import pandas as pd
url = "https://raw.githubusercontent.com/pia222sk20/python/refs/heads/main/data/tellecom.csv"
df=pd.read_csv(url)
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [42]:
import pandas as pd
df.TotalCharges = pd.to_numeric(df.TotalCharges, errors='coerce')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [43]:
df = df.dropna(subset='TotalCharges')
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   object
 1   gender            7032 non-null   object
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   object
 4   Dependents        7032 non-null   object
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   object
 7   MultipleLines     7032 non-null   object
 8   InternetService   7032 non-null   object
 9   OnlineSecurity    7032 non-null   object
 10  OnlineBackup      7032 non-null   object
 11  DeviceProtection  7032 non-null   object
 12  TechSupport       7032 non-null   object
 13  StreamingTV       7032 non-null   object
 14  StreamingMovies   7032 non-null   object
 15  Contract          7032 non-null   object
 16  PaperlessBilling  7032 non-null   object
 17  PaymentMethod     7032 non-null   object
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

In [44]:
#Churn 숫자로 변경 
df.Churn = df.Churn.map({'No':0, 'Yes':1})

In [50]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,0
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1

In [51]:
# # Contract : 범주형 카테고리 변경
df.Contract.unique()
df=pd.get_dummies(df, columns =['Contract'], dtype=float)

In [52]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Contract_Month-to-month,Contract_One year,Contract_Two year
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,Yes,Electronic check,29.85,29.85,0,1.0,0.0,0.0
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,No,Mailed check,56.95,1889.50,0,0.0,1.0,0.0
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,Yes,Mailed check,53.85,108.15,1,1.0,0.0,0.0
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,No,No,No,Bank transfer (automatic),42.30,1840.75,0,0.0,1.0,0.0
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,Yes,Electronic check,70.70,151.65,1,1.0,0.0,0.0

In [53]:
df.describe(exclude='object').corr()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,Churn,Contract_Month-to-month,Contract_One year,Contract_Two year
SeniorCitizen,1.000000,0.999958,0.999911,0.492278,1.000000,1.000000,1.000000,1.000000
tenure,0.999958,1.000000,0.999986,0.499696,0.999958,0.999958,0.999958,0.999958
MonthlyCharges,0.999911,0.999986,1.000000,0.502351,0.999911,0.999911,0.999911,0.999911
TotalCharges,0.492278,0.499696,0.502351,1.000000,0.492297,0.492271,0.492277,0.492277
Churn,1.000000,0.999958,0.999911,0.492297,1.000000,1.000000,1.000000,1.000000
Contract_Month-to-month,1.000000,0.999958,0.999911,0.492271,1.000000,1.000000,1.000000,1.000000
Contract_One year,1.000000,0.999958,0.999911,0.492277,1.000000,1.000000,1.000000,1.000000
Contract_Two year,1.000000,0.999958,0.999911,0.492277,1.000000,1.000000,1.000000,1.000000

In [86]:
X = df.select_dtypes(exclude='object').drop(columns=['Churn', 'SeniorCitizen'])
y = df.Churn   #Churn 'No':0, 'Yes':1

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

clf=LogisticRegression(random_state=42)
clf.fit(X_train, y_train)


# 과적합 확인
    # 두 수치가 차이가 많이 나면 ==> 과적합
    # 과대적합 : 학습>평가 overfitting    
    # 과소적합 : 학습<평가 underfitting   
    # 학습과 평가의 결과 차이가 0.05 이상이면 과적합
y_train_pred = clf.predict(X_train)
print(f'train score : {classification_report(y_train, y_train_pred)}')

y_test_pred = clf.predict(X_test)
print(f'test score (베이스모델) : {classification_report(y_test, y_test_pred)}')


# 베이스 모델 선정
    # 분류모델 : LogisticRegression
    # 클래스 리포트, 과적합여부

train score :               precision    recall  f1-score   support

           0       0.83      0.89      0.86      4130
           1       0.63      0.50      0.56      1495

    accuracy                           0.79      5625
   macro avg       0.73      0.70      0.71      5625
weighted avg       0.78      0.79      0.78      5625

test score (베이스모델) :               precision    recall  f1-score   support

           0       0.83      0.89      0.85      1033
           1       0.61      0.48      0.54       374

    accuracy                           0.78      1407
   macro avg       0.72      0.68      0.70      1407
weighted avg       0.77      0.78      0.77      1407

c:\Users\playdata2\miniconda3\envs\deep\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [87]:
# 베이스 모델의 성능을 상회하는 모델과 하이퍼 파라미터 조합을 찾아서 성능을 출력
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
pipe = Pipeline([
            ('scaler', StandardScaler()),
            ('clf', LogisticRegression(random_state=42, max_iter=10000))
    ])
pipe.fit(X_train, y_train) 
# pipeline_score = pipe.score(X_test, y_test)
    
# 파이프라인 구조
print(f'파이프라인 적용 test score : {classification_report (y_test, pipe.predict(X_test))}')
print(f'train score : {classification_report(y_train, pipe.predict(X_train))}')

파이프라인 적용 test score :               precision    recall  f1-score   support

           0       0.82      0.89      0.86      1033
           1       0.61      0.48      0.54       374

    accuracy                           0.78      1407
   macro avg       0.72      0.68      0.70      1407
weighted avg       0.77      0.78      0.77      1407

train score :               precision    recall  f1-score   support

           0       0.83      0.89      0.86      4130
           1       0.63      0.50      0.56      1495

    accuracy                           0.79      5625
   macro avg       0.73      0.70      0.71      5625
weighted avg       0.78      0.79      0.78      5625

In [88]:
# up sampling SMOTE
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_res, y_res = smote.fit_resample(X_train, y_train)

pipe = Pipeline([
            ('scaler', StandardScaler()),
            ('clf', LogisticRegression(random_state=42, max_iter=10000))
    ])
pipe.fit(X_res, y_res) 
    
# 파이프라인 
print(f'파이프라인 및 SMOTE 적용 (test) : {classification_report (y_test, pipe.predict(X_test))}')
print(f'train score : {classification_report(y_train, pipe.predict(X_train))}')

파이프라인 및 SMOTE 적용 (test) :               precision    recall  f1-score   support

           0       0.91      0.66      0.77      1033
           1       0.47      0.83      0.60       374

    accuracy                           0.71      1407
   macro avg       0.69      0.74      0.68      1407
weighted avg       0.80      0.71      0.72      1407

train score :               precision    recall  f1-score   support

           0       0.92      0.68      0.78      4130
           1       0.49      0.84      0.62      1495

    accuracy                           0.72      5625
   macro avg       0.70      0.76      0.70      5625
weighted avg       0.81      0.72      0.74      5625

In [90]:
X_res.shape, y_res.shape

((8260, 6), (8260,))

In [89]:
# 하이퍼 파라미터 튜닝 이후 pipe 진행/ 최종
from sklearn.model_selection import GridSearchCV
from imblearn.pipeline import Pipeline

X = df.select_dtypes(exclude='object').drop(columns=['Churn', 'SeniorCitizen'])
y = df.Churn   #Churn 'No':0, 'Yes':1

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

# 파이프라인에 상기 SMOTE도 추가
pipe = Pipeline([
            ('scaler', StandardScaler()),
            ('smote', SMOTE(random_state=42)),
            ('clf', LogisticRegression(random_state=42, max_iter=10000))
    ])

param_grid = {
    'clf__C': [0.01, 0.1, 1, 10],
    'clf__solver': ['lbfgs', 'liblinear'],
    'clf__class_weight': [None, 'balanced']
}

grid = GridSearchCV(pipe, param_grid, cv=5, scoring='f1', n_jobs=1)
grid.fit(X_train, y_train)

print("Best F1:", grid.best_score_)
print("Best Params:", grid.best_params_)

# 최종 결과
y_pred = grid.best_estimator_.predict(X_test)
print(f'하이퍼튜닝 & 파이프라인 & SMOTE 적용 : {classification_report (y_test, y_pred)}')
print(f'train score : {classification_report(y_train, grid.best_estimator_.predict(X_train))}')

Best F1: 0.6142693620870192
Best Params: {'clf__C': 10, 'clf__class_weight': None, 'clf__solver': 'liblinear'}
하이퍼튜닝 & 파이프라인 & SMOTE 적용 :               precision    recall  f1-score   support

           0       0.91      0.66      0.76      1033
           1       0.46      0.83      0.59       374

    accuracy                           0.70      1407
   macro avg       0.69      0.74      0.68      1407
weighted avg       0.79      0.70      0.72      1407

train score :               precision    recall  f1-score   support

           0       0.92      0.68      0.78      4130
           1       0.48      0.84      0.61      1495

    accuracy                           0.72      5625
   macro avg       0.70      0.76      0.70      5625
weighted avg       0.80      0.72      0.74      5625

==============================================================

param_grid = {
    'clf__C': [0.01, 0.1, 1, 10],
    'clf__solver': ['lbfgs', 'liblinear'],
    'clf__class_weight': [None, 'balanced']
}


1. clf__C
    - LogisticRegression에서 규제(regularization) 강도를 조절하는 하이퍼파라미터
    - 값이 작을수록 규제가 강하고 → 과적합 줄임
    - 값이 클수록 규제가 약하고 → 모델이 더 자유롭게 학습
    - 후보 [0.01, 0.1, 1, 10] → GridSearchCV가 각각 시도

2. clf__solver
    - LogisticRegression의 최적화 알고리즘 선택
    - 'lbfgs' → 기본, 안정적, 빠름
    - 'liblinear' → 소규모 데이터에 적합, 일부 설정에서 유리
    - 후보 두 가지를 GridSearchCV가 시험해봄

3. clf__class_weight
    - 불균형 클래스 조정
    - None → 기본, 클래스 비율 그대로
    - 'balanced' → 자동으로 클래스 가중치 조정 (소수 클래스 중요도 ↑)
    - 불균형 데이터에서는 F1-score, Recall 개선에 도움

=============================================================

grid = GridSearchCV(pipe, param_grid, cv=5, scoring='f1', n_jobs=-1)

1.  pipe
    - GridSearchCV가 학습시킬 모델을 지정
    - 여기서는 Pipeline 전체를 넣었음

2. param_grid
    - GridSearchCV가 조합을 시험할 하이퍼파라미터 후보 집합

3. cv=5
    - 교차검증(fold) 개수 지정
    - 5 → 5-fold CV
        - 학습 데이터를 5등분
        - 매번 4개 fold 학습, 1개 fold 검증
        - 모든 fold에서 평가 후 평균값으로 성능 측정

4. scoring='f1'
    - 최적화 목표
    - 여기서는 F1-score로 GridSearchCV가 가장 좋은 하이퍼파라미터 선택
    - 다른 예시: 'accuracy', 'roc_auc', 'recall', 'precision' 등

5. n_jobs=-1
    - 병렬 처리 설정
    - -1 → 가능한 모든 CPU 코어 사용
    - GridSearchCV는 후보 조합을 병렬로 학습 가능 → 속도 ↑

In [ ]:
#